name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
        with:
          toolchain: leanprover/lean4:v4.23.0-rc2
      - name: Build
        run: |
          lake update
          lake build Manifest
